import { Factory } from 'rosie'

Factory.define('service.account_database.record.account.1')
    .attr('id', 'account-1')
    .attr('first_name', 'first_name_1')
    .attr('middle_name', 'middle_name_1')
    .attr('last_name', 'last_name_1')
    .attr('contact_number', '09123456789')
    .attr('email_address', 'email_address1@email.com')
    .attr('username', 'username1')
    .attr('password', 'password1')
    .attr('created_at', new Date().toISOString())
    .attr('updated_at', new Date().toISOString())

Factory.define('service.account_database.record.account.2')
    .attr('id', 'account-2')
    .attr('first_name', 'first_name_2')
    .attr('middle_name', 'middle_name_2')
    .attr('last_name', 'last_name_2')
    .attr('contact_number', '09234567890')
    .attr('email_address', 'email_address2@email.com')
    .attr('username', 'username2')
    .attr('password', 'password2')
    .attr('created_at', new Date().toISOString())
    .attr('updated_at', new Date().toISOString())
